server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

# Spring Configuration
spring:
  #to enable colors when you run your app outside intellij
  output:
    ansi:
      enabled: always
  # Database Configuration
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/chatybot?createDatabaseIfNotExist=true
    url: jdbc:postgresql://127.0.0.1:5432/chatybot
    username: karim
    password: karim
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://www.googleapis.com
          client-id: 162871444699-6rcpsihs95urts07e2h0jo9f1dl0bcvr.apps.googleusercontent.com
          client-secret: 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
  ai:
   openai:
     api-key: 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
     embedding:
       options:
         model: text-embedding-ada-002
     chat:
       options:
         temperature: 0.9
  web:
    resources:
      static-locations: classpath:/static/
application:
  token:
    signing:
      key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
      access-token-expiration: 86400000 # 1 day
      refresh-token-expiration: 864000000 # 10 days
  frontend:
    url: http://localhost:4200
#  gemini:
#    chatbots:
#      url: https://generativelanguage.googleapis.com
#      key: AIzaSyBBj4xN9hAX4Zhxv92b8gHLOd1DofNg1ZQ

#  openai:
#    chatbots:
#      url: https://api.openai.com
#      key: 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



